// Per-panel defaults are exported individually so panels can fall back to
// them when a saved settings object predates the key (same idiom as
// WeatherDetailPanel's inline fallback, but with a single source of truth).

// `show` + chrome fields (showHeader/showBackground/backgroundOpacity) drive
// the FloatingPanel wrapper; the rest drive the panel content. Visibility uses
// the `!== false` idiom elsewhere, so an older saved object without `show`
// still reads as visible.
export const newsPanelDefaults = {
  show: true,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.4,
  contentTopGap: 12,
  itemGap: 18,
  indexSize: 26,
  timeSize: 15,
  titleSize: 17,
  summarySize: 13,
  footerSize: 15,
  showIndex: true,
  showTime: true,
  showSource: true,
  showSummary: true,
  showDivider: true,
  showFooter: false,
  highlightLatest: true,
  metaPlacement: 'separate' as 'separate' | 'titleLeft',
  singleLineTitle: true,
  maxItems: 4,
  maxTitleLines: 2,
  maxSummaryLines: 2,
};

export const musicPanelDefaults = {
  show: true,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.4,
  gap: 20,
  showArtwork: true,
  artworkMode: 'topRight' as 'classic' | 'topRight',
  artworkScale: 1,
  artworkCornerSize: 149,
  artworkTopGap: 12,
  artworkProgressGap: 13,
  titleSize: 34,
  artistSize: 16,
  timeSize: 15,
  barHeight: 19,
  showMarker: true,
  pattern: 'diagonal' as 'diagonal' | 'vertical' | 'dot',
  showAlbum: true,
  showTimeCodes: true,
  showControls: false,
  controlSize: 24,
  showFooter: false,
};

export const lyricsPanelDefaults = {
  show: true,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.34,
  contentTopGap: 6,
  showTrack: true,
  showStatus: true,
  align: 'center' as 'left' | 'center' | 'right',
  lineOverflowMode: 'ellipsis' as 'wrap' | 'ellipsis',
  currentSize: 38,
  sideSize: 18,
  metaSize: 12,
  lineGap: 3,
  sideOpacity: 0.45,
  currentMaxLines: 2,
  sideMaxLines: 1,
};

export const personalNewsPanelDefaults = {
  show: false,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.34,
  contentTopGap: 18,
  autoShowWhenLyricsUnavailable: true,
  hideLyricsWhenAutoShown: true,
  showStatus: false,
  personalNewsShowTitle: false,
  personalNewsShowTopic: true,
  personalNewsShowBody: true,
  personalNewsShowSource: true,
  personalNewsShowProgress: false,
  personalNewsShowChapterMarks: true,
  personalNewsTitleSize: 15,
  personalNewsTopicSize: 24,
  personalNewsBodySize: 35,
  personalNewsSourceSize: 12,
  personalNewsProgressHeight: 10,
  personalNewsGap: 12,
  personalNewsScrollSpeed: 1,
  personalNewsSupplementColor: '#b8dcff',
};

export const audioSpectrumPanelDefaults = {
  // Opt-in like personalNews: the audio feed only exists inside Wallpaper
  // Engine, so the panel stays hidden until the user turns it on.
  show: false,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.34,
  contentTopGap: 12,
  barCount: 24,
  segmentCount: 14,
  barGap: 4,
  peakHold: true,
  peakFallSpeed: 0.008,
  sensitivity: 1,
  decaySpeed: 0.12,
  mirror: false,
  colorMode: 'mono' as 'mono' | 'heat',
  showBpm: true,
  bpmMethod: 'pcm-beatroot' as const,
  bpmLockSeconds: 5,
  bpmConfidenceThreshold: 0.7,
  bpmAnalysisWindowSeconds: 14,
  bpmAnalysisIntervalSeconds: 3,
  bpmChangeConfirmSeconds: 9,
  bpmPeriodicResetMinutes: 0,
  bpmResetOnSpotifyTrackChange: true,
  // User taste adjustment added to the LOCKED bpm only (display + kiritan sync).
  // Detection itself always runs on the raw signal.
  bpmOffset: 0,
  rhythmMotionEnabled: true,
  rhythmMotionStrength: 0.35,
  // Keep the selected one-BPM motion bank alive through brief detector gaps.
  rhythmMotionHoldSeconds: 8,
  // In normal work mode, use a faint head/neck-only nod (no torso or hands).
  workHeadSyncEnabled: true,
  workHeadSyncStrength: 0.35,
  standbyText: 'AUDIO STANDBY',
};

export const memoPanelDefaults = {
  show: true,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.4,
  contentTopGap: 9,
  textSize: 21,
  dateSize: 12,
  cardGap: 14,
  cardPadding: 6,
  showDates: false,
  showPinnedSection: true,
  showFooter: false,
  maxLines: 0,
  maxItems: 0,
};

export const timerPanelDefaults = {
  show: true,
  showHeader: true,
  showBackground: true,
  backgroundOpacity: 0.4,
  contentTopGap: 18,
  mode: 'pomodoro' as 'timer' | 'pomodoro',
  timerTitle: 'Countdown',
  focusTitle: 'Pomodoro',
  shortBreakTitle: 'Rest',
  longBreakTitle: 'Long Rest',
  timerLabel: 'TIMER',
  focusLabel: 'FOCUS',
  shortBreakLabel: 'BREAK',
  longBreakLabel: 'LONG BREAK',
  timerMinutes: 10,
  pomodoroMinutes: 25,
  shortBreakMinutes: 5,
  longBreakMinutes: 15,
  titleSize: 15,
  timeSize: 53,
  metaSize: 13,
  barHeight: 10,
  itemGap: 6,
  showControls: false,
  showCycle: true,
  timerPresets: [] as Array<Record<string, unknown>>,
};

export const uiSettings = {
  debugMode: false,
  baseResolution: '1920x1200',
  clock: {
    showClock: true,
    showDate: true,
    showSeconds: true,
    showWeather: true,
    showHumidity: true,
    showLocation: true,
    showBackground: false,
    backgroundOpacity: 0.28,
    paddingX: 0,
    paddingY: 0,
    dateOffsetX: 10,
    customLocation: "SAPPORO",
    customWeatherTemp: "18°C",
    customWeatherDesc: "CLOUDY",
    customHumidity: "HUMID 62%",
  },
  weatherCompact: {
    showCompactWeather: true,
    displayMode: 'compact' as 'compact' | 'detailed',
    showLocation: true,
    showWeather: true,
    showTemperature: true,
    showHumidity: true,
    showPressure: true,
    showMinMaxLabels: false,
    showCurrentMarker: true,
    showCurrentTriangle: true,
    showBackground: false,
    backgroundOpacity: 0.28,
    infoRowPosition: 'top' as 'top' | 'bottom',
    temperaturePadding: 5,
    pattern: "diagonal" as const,
  },
  weatherDetail: {
    gap: 10,
    fontSize: 1,
    paddingTop: 16,
    paddingBottom: 7,
    paddingX: 11,
    mainTempSize: 88,
    minMaxTempSize: 35,
    feelsLikeSize: 23,
    metricLabelSize: 19,
    metricValueSize: 19,
    windSunSize: 34,
    noteSize: 21,
    maxNoteLines: 0,
    footerSize: 20,
    mainIconSize: 92,
    compassSize: 91,
    sunIconSize: 37,
    showBackground: false,
    backgroundOpacity: 0.4,
    pattern: "dot" as const,
  },
  newsPanel: newsPanelDefaults,
  musicPanel: musicPanelDefaults,
  lyricsPanel: lyricsPanelDefaults,
  personalNewsPanel: personalNewsPanelDefaults,
  audioSpectrumPanel: audioSpectrumPanelDefaults,
  memoPanel: memoPanelDefaults,
  timerPanel: timerPanelDefaults,
  overlay: {
    opacity: 1.0,
    fpsLimit: 60,
  },
  wallpaper: {
    backgroundImageEnabled: true,
    backgroundImageDataUrl: "/backgrounds/sample-kobe-night.jpg",
    backgroundFit: "cover" as "cover" | "contain",
    modelLightScale: 2.45,
    modelVisible: true,
    vrmModelPath: "",
    propPhoneVisible: true,
    propControllerVisible: true,
    propCupVisible: true,
    cameraAdjustmentEnabled: true,
    cameraX: -0.25,
    cameraY: 0,
    cameraZ: -0.05,
    cameraYaw: -2,
    cameraPitch: -2,
    cameraRoll: 0,
    cameraMoveStep: 0.05,
    cameraRotateStep: 1,
    backgroundMode: "single" as "single" | "slideshow" | "video" | "videoSlideshow",
    backgroundTransition: "fade" as "loop" | "fade" | "advance",
    backgroundQueue: [] as Array<string | { url: string; type?: "image" | "video"; name?: string; presetId?: string }>,
    backgroundOverlays: [] as Array<{
      url: string;
      name?: string;
      visible?: boolean;
      opacity?: number;
      blendMode?: "normal" | "screen" | "multiply" | "overlay" | "soft-light" | "lighten" | "darken";
      fit?: "cover" | "contain";
    }>,
    backgroundQueueIntervalSeconds: 60,
    backgroundQueueFadeSeconds: 1,
    backgroundVideoMuted: true,
    objectLayout: {
      character: { position: [0, 0, 0], rotation: [0, 0, 0], scale: [1, 1, 1] },
      desk: { position: [0, 0, 0.47], rotation: [0, 3.14, 0], scale: [0.927, 0.927, 0.927] },
      chair: { position: [-9.066, 0, 5.627], rotation: [0, 0, 0], scale: [0.027, 0.027, 0.027] },
      laptop: { position: [-0.03, 0.72, 0.24], rotation: [0, 1.569, 0], scale: [0.34, 0.34, 0.34] },
    },
    itemLayout: {
      "item:cup": { position: [0.28, 0.73, 0.2], rotation: [0, 3.13, 0], scale: [0.037, 0.037, 0.037] },
      "item:phone": { position: [0.39, 0.73, 0.21], rotation: [0, 0.6, 0], scale: [0.66578, 0.66578, 0.66578] },
      "item:controller": { position: [0.31, 0.74, 0.36], rotation: [0, 2.35, 1.53], scale: [0.017, 0.016, 0.017] },
      "item:book": { position: [-0.5, 0.7511, 0.28], rotation: [0, 0, 0], scale: [0.23976, 0.23976, 0.23976] },
      "item:headphones": { position: [-0.6214, 0.7363, 0.52], rotation: [0, 0, 0], scale: [0.17767, 0.17767, 0.17767] },
      "item:snack_plate": { position: [0.1208, 0.7271, 0.1475], rotation: [0, 0, 0], scale: [0.48711, 0.48711, 0.48711] },
    },
  },
  motion: {
    directorMode: "fixed" as "auto" | "fixed",
    fixedMode: "work_normal",
    modeMinMinutes: 15,
    modeMaxMinutes: 30,
    motionMinSeconds: 90,
    motionMaxSeconds: 240,
    disabledModes: [] as string[],
    disabledMotions: [] as string[],
  },
};
